apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 7.0.0
    helm:
      valuesObject:
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          limits_config:
            retention_period: 72h
            reject_old_samples: true
            reject_old_samples_max_age: 168h
          analytics:
            reporting_enabled: false
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: local-path
            size: 5Gi
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        lokiCanary:
          enabled: false
        test:
          enabled: false
        gateway:
          enabled: false
        minio:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
