apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bitnami.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.19.3
    helm:
      valuesObject:
        fullnameOverride: sealed-secrets-controller
        resources:
          requests:
            cpu: 25m
            memory: 48Mi
          limits:
            cpu: 200m
            memory: 128Mi
        metrics:
          serviceMonitor:
            enabled: true
            namespace: kube-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
