---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-secret
  namespace: ai
spec:
  encryptedData:
    master-key: AgCd7Cd/JQkeZtPzXEbsmvAcX6ZQuCEcptmx90Sclsq02gxAjFyhdACgctWZLji91CHWq+1iuqEH/Vpn4pBSZikJ43roHLs11k4Hv8/6mshI8Ib9PtO1vjH8UlCX5OMspqrNR7WK5QTltUytYkFnvXYdORyNeItIFHMK77PIrkxA5Y53Wxl6pDUJ+YPlVfbBJgDfBymActGLuRBsN87D+kzyq1KjE6CMiJ1heMvRpvMhI8wjX5dHvZRuXaZD6u3VEwD73Dt35DF1ur8Znvdw838V3XhwYWqRLiGzSSRLtXaeKf24yncGYT2431qnp14Pzyojgi5jyse3ducJeH9H/zH29WnCM1/Ajg3WifGuhz1lY8HRXYSCD/sFf7/5IAwCPkje+xvhU8lcqCjByundW/MKEn91yY6sGi/I+im5sx76HTcGjSYN+vxbB9y/UQEf96CjhOGAe0A7LcuMFJbi1ePEePB0IG/1jbiR7cWaZheCUqEVNCuuuGJT+Ru8CYOEMZB8S4KOSXm54G2mWaMeJ5xW3eSIUUOBKNt7TAeDfuhReBMMvrlJ5AVpD9erUNQ7vN3dZY08CBDo3AFzCkh5nGTmZf8Qc1qdbYYCtt5r4DPHDDy/nGa7YDQKg4ii+BXA39klCVAngfb7t7flEn82SAsUPU4k0okmJ/OVURxKCmPXJ8OWPrqqMndDV4ob0eLpZF4Elz5Mpgj5hhttaYwOJ8eyeaPh62W4cMlwGWKDS41M31JIWRpNpIe+77mnqYtqsrlck14=
  template:
    metadata:
      name: litellm-secret
      namespace: ai
    type: Opaque
